name: 'Build Highcharts'
description: 'Builds highcharts'
inputs:
  dashboards:  # id of input
    description: 'Also build dashboards'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'npm'

    - run: npm i
      shell: bash
    - run: npx gulp scripts
      shell: bash

    - run: npx gulp dashboards/scripts
      shell: bash
      if: ${{ inputs.dashboards == true }}
